### ISSUE TITLE
Grade "loading" hangs

### ISSUE THREAD

**Issue by gregoryg22** [aopell/SchoologyPlus#21]
English grade says loading, never had this issue before.

https://prnt.sc/jdydp3 

^kinda low quality, let me know if you need anything else.

**Comment by glen3b** [comment]
I can't reproduce this in Firefox with the same course, for me that class loads correctly and doesn't stick on a loading indicator. Does the loading indicator stick around or is the issue transient? Are you using Chrome? On what platform? Are you able to consistently reproduce the issue?

If you can consistently reproduce the issue, can you please attach the log from the [JavaScript console](https://developers.google.com/web/tools/chrome-devtools/console/)? Open the console, reload the page, and once the page is loaded, copy-paste the log into a pastebin or similar.

**Comment by gregoryg22** [comment]
its been doing this since yesterday (just staying on loading and not resolving) on Google Chrome Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by gregoryg22** [comment]
should be latest http://prntscr.com/jdyquz

**Comment by aopell** [comment]
Could either of you (@gregoryg22 @glen3b) send screenshots of the assignment pages for both "AP Lang Test IN CLASS" and "Style Provision Love Essay"

I have a feeling it's one of the following:
 - Something breaks when an assignment is both missing and dropped
 - The assignment has a strange point denominator (possibly 0?)
 - The rate limit is being hit, causing the background request for a point total to reach a page that isn't the assignments page

I think the third is pretty likely given the error above since it can't find an element with class `.max-points`.

**Comment by glen3b** [comment]
Hopefully 0 denominator wouldn't break, because that's what extra credit assignments have.
For me, the assignment is neither missing nor dropped; the page works properly for me. That said we should have the same assignment.

The "AP Lang Test IN CLASS" no longer exists, our teacher may have renamed or removed it.

Style Revision Love Essay assignment header:
![Assignment header for Style Revision Love Essayh](https://i.imgur.com/Dxs6XE2.png)

**Comment by aopell** [comment]
I believe I figured out the cause of this issue using one of my past courses. It seems that sometimes the assignment page doesn't show the maximum points for an assignment when it's missing. I don't know what the best way to work around this is besides not counting it. I don't know any other way of determining the max points.

![image](https://user-images.githubusercontent.com/5026980/39716510-6c5ede12-51e5-11e8-91fc-7b38af7bc517.png)

**Comment by aopell** [comment]
Promising solution: Schoology has a REST API

**Comment by aopell** [comment]
This solution is very hacky, but I think it's the best I can do. The extension generates an API key for the user if they don't already have one and makes a request for the missing assignment to the API using that key.

The API has a lot of potential use cases, including a way to get more information about assignments or courses etc. than is available through the interface. One interesting but painful idea is a major rewrite of a lot of the current functionality of Schoology Plus to make use of the API.

@glen3b
