### ISSUE TITLE
Interferes with other custom CSS

### ISSUE THREAD

**Issue by KTibow** [aopell/SchoologyPlus#236]
**Describe the bug**
I currently use [schoology.css](https://ktibow.github.io/schoology.css) for Schoology as well. However SchoologyPlus makes it look weird:
https://imgur.com/a/GljhdCH
It also changes the hue back:
![image](https://user-images.githubusercontent.com/10727862/103708029-96303e00-4f64-11eb-8e8f-9cab7109e67e.png)

**To Reproduce**
1. Install [schoology.css](https://ktibow.github.io/schoology.css)
2. See bad layout

**Expected behavior**
Stuff stays the same except some stuff is added.

**Screenshots**
![image](https://user-images.githubusercontent.com/10727862/103708118-ce378100-4f64-11eb-87fe-df6ff7b559f3.png)
![image](https://user-images.githubusercontent.com/10727862/103708128-d68fbc00-4f64-11eb-93c0-bfcde8a478e2.png)
![image](https://user-images.githubusercontent.com/10727862/103708141-db547000-4f64-11eb-85a0-a9ee2575e38f.png)
![image](https://user-images.githubusercontent.com/10727862/103708150-e0192400-4f64-11eb-8d6d-f4e9e359579e.png)
![image](https://user-images.githubusercontent.com/10727862/103708163-e5766e80-4f64-11eb-9caa-50b2bc30b7e7.png)

**Additional context**
I could update schoology.css to handle this issue; however it would take a lot of work to understand the giant source code of schoology+.

**Comment by aopell** [comment]
Hi, thanks for leaving this issue! I took a look at your schoology.css project and it looks a lot like what we're trying to do with our new modern theme engine (including our new premade dark and light themes as well as our custom theme editor). 

Because of the complexity of our CSS across both versions of our theme engine as well as our general CSS tweaks unrelated to theming, it's not likely we're going to support other Schoology extensions (or user scripts/styles).

That being said, if you'd like to contribute some of your ideas from your schoology.css into Schoology Plus directly, we'd be happy to work with you in [our Discord server](http://discord.schoologypl.us), it looks great!

Also if you'd like to try out our modern themes, you can [join our dark theme beta test here](https://schoologypl.us/docs/beta/darktheme) and let us know what you think in Discord or here on GitHub.

I'm going to mark this issue as a discussion for now, but just so you're aware it's very likely a wontfix due to its complexity.

**Comment by KTibow** [comment]
Got it. I've noticed that you use CSS vars, so I could modify them. I've fixed most of it by adding this:
```
body {
  --primary-color: var(--background);
  --link-color: var(--color);
  --hover-color: transparent;
  --border-color: transparent;
  --background-url: none;
}
body a.link-btn, ul.tabs li a {
  color: var(--text) !important;
}
footer li a, header li a, .splus-modal-footer-text a, body a.link-btn.active, div.courses-left-menu, .portfolio-list a.btn, a._3_bfp {
  color: var(--color) !important;
}
```
Result:
![image](https://user-images.githubusercontent.com/10727862/103722233-5a0cd580-4f84-11eb-81e4-7d9de4c75d5c.png)
![image](https://user-images.githubusercontent.com/10727862/103722244-63963d80-4f84-11eb-92ae-7d107323aaeb.png)
![image](https://user-images.githubusercontent.com/10727862/103722256-6bee7880-4f84-11eb-9e17-ddf1049d2d3f.png)
![image](https://user-images.githubusercontent.com/10727862/103722268-6f81ff80-4f84-11eb-8f47-a6e7615f5d51.png)
![image](https://user-images.githubusercontent.com/10727862/103722288-77da3a80-4f84-11eb-952b-97434931b018.png)
I'll update the original issue. Surprised how simple this was.

**Comment by aopell** [comment]
Great! I'm going to mark this as closed for now.
