### ISSUE TITLE
Theme does not apply to text input on discussion posts

### ISSUE THREAD

**Issue by DarkBrave** [aopell/SchoologyPlus#262]
### Describe the bug
Theme does not apply to input/text boxes on discussion posts.

### Steps to reproduce

1. Apply a custom color theme (dark mode in my case)
2. Go to a discussion post in a course or group
3. Click on the "write a comment" field
4. Theme does not apply

### Expected behavior
I expected Schoology Plus to apply the dark mode theme to the text/input box on discussions, allowing you to use the input fields with your custom (or built-in) theme.

### Screenshots
![image](https://user-images.githubusercontent.com/43324814/132532802-55fecf30-999c-4685-a657-aa51db29445d.png)

### Platform
Firefox 91, Schoology Plus v7.2.4, Windows 10 Education 20H2

**Comment by aopell** [comment]
This is actually intentional. Basically, for rich input boxes like the ones for discussion posts, we don't want to theme it because it would show differently on your screen to how it would look to someone who doesn't have Schoology Plus installed (like probably your teacher). We just don't want it to cause issues where someone writes text that doesn't show up correctly to someone using a light theme/doesn't have S+.

**Comment by DarkBrave** [comment]
Makes sense now that I think about it.
