### ISSUE TITLE
Grade page script fails in Firefox on async fetch with third-party cookies disabled

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#27]
A strange **warning** (not error) prevents the script from loading on Firefox regarding an unbalanced tree written with `document.write()`

![image](https://user-images.githubusercontent.com/5026980/40738859-77b08a1a-63f9-11e8-894e-a09ab597c6e6.png)

Reported by @89bryan

**Comment by aopell** [comment]
Upon further inspection, this appears to be an issue with the `async` call to `fetch` on line 45 of `grades.js`

This may have to do with strict browser security settings set by the end user

**Comment by aopell** [comment]
Cannot reproduce on Firefox 60.0.1 with default settings

**Comment by glen3b** [comment]
The warnings are unrelated; I recognize them from my Firefox install without issues. I bet the warning has to do with the way announcements are implemented, as crude document.write calls (which should be reworked), but that's not this issue.

I suspect that the issue is indeed the security configuration of @89bryan's browser.

@89bryan: can you make sure the following domains all use the same set of cookies:
- `lms.lausd.net`
- `*.schoology.com`
- `api.schoology.com`

**Comment by aopell** [comment]
The issue is most likely related to third party cookies being disabled. This should be addressed by error handling in the case of an API call failure. The main functionality of the extension still works fine without third party cookies.

Potentially merge with #26?

**Comment by glen3b** [comment]
I get a similar issue in Firefox (no error message, grade loading failes to complete, but does log API key fetch call) with third-party cookies disabled. Definitely related to error handling.
