### ISSUE TITLE
Discussion: Remove checkbox for grade modification?

### ISSUE THREAD

**Issue by aopell** [aopell/SchoologyPlus#80]
Considering all actions for modifying grades require a click anyway, is there really a point of it existing?

**Comment by glen3b** [comment]
If I recall correctly its primary purpose was to help with UI clutter, since the majority (but not all) of grade page visits will not be for edits.
In this context a global setting doesn't make sense.
Especially with the kebab menu I think a setting to manage visual complexity is helpful.
That said, the primary downside of it existing as I see it is code complexity, coming in two parts:
- Behavioral differences between edit and nonedit pages
- Display (e.g. hiding edit components) variations

The former point I don't think can be improved hugely from what we have now, but the latter we currently do in JS and I think it's worth investigating a more CSS-heavy way which avoids duplicating logic in JS (using CSS variables perhaps? I'm not terribly familiar with them).

**Comment by aopell** [comment]
Ok, so I think we'll close this for now then
